# Generated by Django 2.1.2 on 2018-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
